-- Actualización de módulos y permisos para producción
-- Solo ejecuta este archivo en tu base de datos, no crea tablas

-- Módulos nuevos
INSERT INTO `modules` (`name`, `slug`, `description`, `icon`, `color`, `url`, `status`, `created_at`, `updated_at`) VALUES
('Inventario', 'inventory', 'Gestión de productos y stock', 'fas fa-boxes', '#2ecc71', '/modules/inventory/', 'active', NOW(), NOW()),
('Formularios', 'forms', 'Creación y gestión de formularios', 'fas fa-file-alt', '#3498db', '/modules/forms/', 'active', NOW(), NOW()),
('Capacitación', 'training', 'Gestión de cursos y empleados asignados', 'fas fa-chalkboard-teacher', '#f39c12', '/modules/training/', 'active', NOW(), NOW()),
('Vehículos', 'vehicles', 'Registro y control de vehículos', 'fas fa-car', '#e67e22', '/modules/vehicles/', 'active', NOW(), NOW()),
('Inmuebles', 'properties', 'Registro y gestión de inmuebles', 'fas fa-home', '#9b59b6', '/modules/properties/', 'active', NOW(), NOW()),
('Limpieza', 'cleaning', 'Asignación de rutinas de limpieza', 'fas fa-broom', '#1abc9c', '/modules/cleaning/', 'active', NOW(), NOW()),
('Lavandería', 'laundry', 'Registro de cargas de lavandería', 'fas fa-tshirt', '#e74c3c', '/modules/laundry/', 'active', NOW(), NOW()),
('Transporte', 'transportation', 'Programación de traslados', 'fas fa-bus', '#34495e', '/modules/transportation/', 'active', NOW(), NOW()),
('Chat', 'chat', 'Comunicación interna y conversaciones', 'fas fa-comments', '#3498db', '/modules/chat/', 'active', NOW(), NOW()),
('Facturación', 'invoicing', 'Emisión y gestión de facturas', 'fas fa-file-invoice', '#f39c12', '/modules/invoicing/', 'active', NOW(), NOW()),
('Analítica', 'analytics', 'Generación de escenarios y KPIs', 'fas fa-chart-bar', '#9b59b6', '/modules/analytics/', 'active', NOW(), NOW()),
('Punto de Venta', 'pos', 'Registro de ventas y cobros', 'fas fa-cash-register', '#2ecc71', '/modules/pos/', 'active', NOW(), NOW()),
('CRM', 'crm', 'Gestión de clientes y etapas', 'fas fa-user-tie', '#e67e22', '/modules/crm/', 'active', NOW(), NOW()),
('Caja Chica', 'petty-cash', 'Solicitudes y control de fondos', 'fas fa-wallet', '#e74c3c', '/modules/petty-cash/', 'active', NOW(), NOW()),
('Configuración', 'settings', 'Edición de empresa y módulos', 'fas fa-cogs', '#34495e', '/modules/settings/', 'active', NOW(), NOW()),
('KPIs', 'kpis', 'Visualización de indicadores clave', 'fas fa-bullseye', '#3498db', '/modules/kpis/', 'active', NOW(), NOW()),
('Agente de Ventas', 'sales-agent', 'Recomendaciones IA para ventas', 'fas fa-robot', '#f39c12', '/modules/sales-agent/', 'active', NOW(), NOW()),
('Mantenimiento', 'maintenance', 'Gestión y cierre de servicios', 'fas fa-tools', '#2ecc71', '/modules/maintenance/', 'active', NOW(), NOW());

-- Permisos base para cada módulo
INSERT INTO `permissions` (`key_name`, `description`, `module`, `created_at`) VALUES
('inventory.view', 'Ver inventario', 'inventory', NOW()),
('inventory.create', 'Agregar producto', 'inventory', NOW()),
('inventory.edit', 'Editar producto', 'inventory', NOW()),
('inventory.delete', 'Eliminar producto', 'inventory', NOW()),
('forms.view', 'Ver formularios', 'forms', NOW()),
('forms.create', 'Crear formulario', 'forms', NOW()),
('forms.edit', 'Editar formulario', 'forms', NOW()),
('forms.delete', 'Eliminar formulario', 'forms', NOW()),
('training.view', 'Ver cursos', 'training', NOW()),
('training.create', 'Crear curso', 'training', NOW()),
('training.edit', 'Editar curso', 'training', NOW()),
('training.delete', 'Eliminar curso', 'training', NOW()),
('vehicles.view', 'Ver vehículos', 'vehicles', NOW()),
('vehicles.create', 'Registrar vehículo', 'vehicles', NOW()),
('vehicles.edit', 'Editar vehículo', 'vehicles', NOW()),
('vehicles.delete', 'Eliminar vehículo', 'vehicles', NOW()),
('properties.view', 'Ver inmuebles', 'properties', NOW()),
('properties.create', 'Registrar inmueble', 'properties', NOW()),
('properties.edit', 'Editar inmueble', 'properties', NOW()),
('properties.delete', 'Eliminar inmueble', 'properties', NOW()),
('cleaning.view', 'Ver rutinas', 'cleaning', NOW()),
('cleaning.create', 'Asignar rutina', 'cleaning', NOW()),
('cleaning.edit', 'Editar rutina', 'cleaning', NOW()),
('cleaning.delete', 'Eliminar rutina', 'cleaning', NOW()),
('laundry.view', 'Ver cargas', 'laundry', NOW()),
('laundry.create', 'Registrar carga', 'laundry', NOW()),
('laundry.edit', 'Editar carga', 'laundry', NOW()),
('laundry.delete', 'Eliminar carga', 'laundry', NOW()),
('transportation.view', 'Ver traslados', 'transportation', NOW()),
('transportation.create', 'Programar traslado', 'transportation', NOW()),
('transportation.edit', 'Editar traslado', 'transportation', NOW()),
('transportation.delete', 'Eliminar traslado', 'transportation', NOW()),
('chat.view', 'Ver conversaciones', 'chat', NOW()),
('chat.create', 'Iniciar conversación', 'chat', NOW()),
('chat.edit', 'Editar conversación', 'chat', NOW()),
('chat.delete', 'Eliminar conversación', 'chat', NOW()),
('invoicing.view', 'Ver facturas', 'invoicing', NOW()),
('invoicing.create', 'Emitir factura', 'invoicing', NOW()),
('invoicing.edit', 'Editar factura', 'invoicing', NOW()),
('invoicing.delete', 'Eliminar factura', 'invoicing', NOW()),
('analytics.view', 'Ver escenarios', 'analytics', NOW()),
('analytics.create', 'Generar escenario', 'analytics', NOW()),
('analytics.edit', 'Editar escenario', 'analytics', NOW()),
('analytics.delete', 'Eliminar escenario', 'analytics', NOW()),
('pos.view', 'Ver ventas', 'pos', NOW()),
('pos.create', 'Registrar venta', 'pos', NOW()),
('pos.edit', 'Editar venta', 'pos', NOW()),
('pos.delete', 'Eliminar venta', 'pos', NOW()),
('crm.view', 'Ver clientes', 'crm', NOW()),
('crm.create', 'Registrar cliente', 'crm', NOW()),
('crm.edit', 'Editar cliente', 'crm', NOW()),
('crm.delete', 'Eliminar cliente', 'crm', NOW()),
('petty-cash.view', 'Ver caja chica', 'petty-cash', NOW()),
('petty-cash.create', 'Solicitar fondo', 'petty-cash', NOW()),
('petty-cash.edit', 'Editar solicitud', 'petty-cash', NOW()),
('petty-cash.delete', 'Eliminar solicitud', 'petty-cash', NOW()),
('settings.view', 'Ver configuración', 'settings', NOW()),
('settings.edit', 'Editar configuración', 'settings', NOW()),
('kpis.view', 'Ver KPIs', 'kpis', NOW()),
('sales-agent.view', 'Ver recomendaciones', 'sales-agent', NOW()),
('sales-agent.create', 'Generar recomendación', 'sales-agent', NOW()),
('maintenance.view', 'Ver servicios', 'maintenance', NOW()),
('maintenance.create', 'Completar servicio', 'maintenance', NOW()),
('maintenance.edit', 'Editar servicio', 'maintenance', NOW()),
('maintenance.delete', 'Eliminar servicio', 'maintenance', NOW());
