ALTER TABLE providers
  ADD COLUMN phone VARCHAR(20) NULL,
  ADD COLUMN email VARCHAR(255) NULL,
  ADD COLUMN address TEXT NULL,
  ADD COLUMN rfc VARCHAR(13) NULL,
  ADD COLUMN created_by INT UNSIGNED NULL;
