name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --no-progress --no-interaction
      - name: Run PHP_CodeSniffer
        run: composer lint
